#!/usr/bin/env sh

set -e

chmod -R a+rwx $(pwd)/.git
mkdir -p "$(pwd)/.git/hooks"

if [ -e "$(pwd)/.git/hooks/pre-commit" ]; then
    echo ".git/hooks/pre-commit has been detected, renews the file forcefully."
    rm -rf "$(pwd)/.git/hooks/pre-commit"
fi

curl -s https://raw.githubusercontent.com/yabe-diverta/enforcing-textlint-lp/main/pre-commit --output "$(pwd)/.git/hooks/pre-commit"

chmod -R a+rwx $(pwd)/.git
